services:
  db:
    image: "mysql:8.4"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USERNAME: 'root'
      MYSQL_PASSWORD: 'root'
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    ports:
      - "3307:3306"

  autonium:
    depends_on:
      - "db"
    build:
      context: .
    ports:
      - "3000:3000"
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: 'root'
      DB_PASSWORD: 'root'
      DB_NAME: 'demo_autoium'
    volumes:
      - ".:/app"

volumes:
  db: