json.id test_case.id
json.action test_case.action
json.name test_case.description
json.description test_case.description
json.action_url test_case.action_url
json.base_url test_case.base_url
json.action_url test_case.action_url
json.custom_command_id test_case.custom_command_id
json.dependency test_case.dependency
json.element_class test_case.element_class
json.enter_action test_case.enter_action
json.field_name test_case.field_name
json.field_type test_case.field_type
json.full_xpath test_case.full_xpath
json.input_value test_case.input_value
json.need_screenshot test_case.need_screenshot
json.new_tab test_case.new_tab
json.priority test_case.priority
json.sleeps test_case.sleeps
json.read_element test_case.read_element
json.string test_case.string
json.xpath test_case.xpath