default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%#= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DB_NAME'] %>
  #database: mecc24_reg_local
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  variables:
    sql_mode: TRADITIONAL

  #development:
  #<<: *default
  #username: root
  #password: root
  #host: 127.0.0.1

development:
  <<: *default
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>


